### PR TITLE
Fix MCTS pt. 1

### LINKED ISSUE #8: Catch IllegalStateExceptions in BattleSimulation
In #7 MCTS was implemented, but sometimes throws `IllegalStateException` if we run into a state that shouldn't occur.
We haven't experienced any of these yet, but it would probably be better to catch these in `BattleSimulation` so that the game doesn't crash. 
However, if this happens we need to decide if we want the AI to make no move or do a random move so the game doesn't get stuck.

### PR DESCRIPTION
**Pull request by IsabellaNorup**
This PR adds better an improved MCTS algorithm. Fixes lots of issues. Too many to describe here. Have a look at the code.

This PR also adds some `toString()` methods that make debugging much easier. It also adds some verbose logging to MCTS that shows the result of the algorithm in the console.

At last, this PR solves #8

### CODE REVIEW

File: src/main/java/dk/sdu/mmmi/modulemon/BattleSimulation/BattleSimulation.java [hunk 1]
```diff
@@ -268,30 +263,48 @@ public boolean hasNextBattleEvent() {
...
     }
 
+    private void doOpponentMove() {
+        AIExecutor.execute(() -> {
+            try {
+                getOpponentAI().doAction();
+            } catch (Exception ex) {
+                System.out.println(ex);
+                nextEvent = new AICrashedEvent(String.format("The opponent %s controller has crashed!", this.opponentAIFactory), this.battleState.getActiveParticipant(), ex, battleState.clone());
+                onNextEvent = this::switchTurns;
```
Comment (VictorABoye) [inline src/main/java/dk/sdu/mmmi/modulemon/BattleSimulation/BattleSimulation.java:282]: Nice, that we gracefully are able to get out of a battle if the AI crashes

File: src/main/java/dk/sdu/mmmi/modulemon/MCTSBattleAI/MCTSBattleAI.java [hunk 2]
```diff
@@ -24,7 +24,8 @@ public class MCTSBattleAI implements IBattleAI {
     private long startTime;
     private int defaultTimeLimitMs = 1000;
     private IGameSettings settings = null;
-    private final int MAX_SIMULATE_DEPTH = 20;
+    private long timeLimit = defaultTimeLimitMs;
+    private final int MAX_SIMULATE_DEPTH = 5;
```
Comment (VictorABoye) [inline src/main/java/dk/sdu/mmmi/modulemon/MCTSBattleAI/MCTSBattleAI.java:28]: This seems pretty low. Is this from debugging or how did you decide on depth of 5?

**Review by VictorABoye — COMMENTED** [review]
Nice changes, though the change to `MAX_SIMULATE_DEPTH` confused me a bit since it seems pretty shallow compared with minimax depth

File: src/main/java/dk/sdu/mmmi/modulemon/MCTSBattleAI/MCTSBattleAI.java (hunk 2 above)
Comment (IsabellaNorup) [reply src/main/java/dk/sdu/mmmi/modulemon/MCTSBattleAI/MCTSBattleAI.java:28]: Partly from debugging and partly because I found that it seemed to make better decisions the lower this was. 
Maybe `5` is indeed too low, but it also seems like `20` is too much. 
I think it's something we have to experiment a bit with.

Comment (VictorABoye) [reply src/main/java/dk/sdu/mmmi/modulemon/MCTSBattleAI/MCTSBattleAI.java:28]: Hmm, alright. Though MCTS is supposed to simulate games to the end, so I would think having a deeper search(optimally till terminal state) would be a more *real* implementation of MCTS. But this seems fine for now, and then we can tinker a bit more with it.
